name: event_planner
description: "This project is owned by Matheus Kikumori & CJSP"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: 
  provider: 
  flutter_lints: 
  firebase_auth: 
  cloud_firestore: 
  firebase_core:
  firebase_storage: 
  image_picker: 
  shared_preferences:

flutter:
  uses-material-design: true

  assets:
    - assets/animations/music_icon.gif
    - assets/images/clave_de_sol.jpg
  